name: Test
on: 
  push:
    branches: 
      - 'main'
  pull_request:
    branches:
      - 'main'

permissions:
  contents: read

jobs: 
  test-main:
    name: test main
    if: |
      github.event_name == 'push' &&
      github.ref_name == 'main'
    runs-on: ubuntu-22.04
    steps:
      - run: echo "${{ github.event_name }}"
      - run: echo "Hello from the ${{ github.ref_name }}"
      - run: echo "hello world tfplan" >> tfplan
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ github.run_id }}-tf-plan
          path: ./tfplan

  test-pr:
    name: test pull request
    needs: test-main
    runs-on: ubuntu-22.04
    steps:
      - run: echo "${{ github.event_name }}"
      - run: echo "Hello from the ${{ github.ref_name }}"
      - uses: actions/download-artifact@v3
        with:
          name: ${{ github.run_id }}-tf-plan
          path: ./tfplan
      - run: cat ./tfplan
